export const RASHI_SLUG_TO_NAME: Record<string, string> = {
  mesh: 'Mesha',
  vrishabh: 'Vrishabha',
  mithun: 'Mithuna',
  kark: 'Karka',
  simha: 'Simha',
  kanya: 'Kanya',
  tula: 'Tula',
  vrishchik: 'Vrishchika',
  dhanu: 'Dhanu',
  makar: 'Makara',
  kumbh: 'Kumbha',
  meen: 'Meena',
};

export const RASHI_NAME_TO_SLUG: Record<string, string> = Object.fromEntries(
  Object.entries(RASHI_SLUG_TO_NAME).map(([slug, name]) => [name, slug])
);

export const RASHI_SLUGS_ORDER = [
  'mesh','vrishabh','mithun','kark','simha','kanya',
  'tula','vrishchik','dhanu','makar','kumbh','meen',
];

export interface VedicSignExtended {
  full_description: string;
  jyotish_tradition: string;
  ruling_planet_detail: string;
  lucky_gemstone: string;
  gemstone_detail: string;
  favorable_days: string[];
  ayurveda_connection: string;
  famous_people: Array<{ name: string; born: number }>;
  strengths_detail: string;
  challenges_detail: string;
  in_love: string;
  in_career: string;
  compatible_rashis: string[];
  faq: Array<{ q: string; a: string }>;
}

export const VEDIC_SIGN_EXTENDED: Record<string, VedicSignExtended> = {
  mesh: {
    full_description: `Mesha Rashi (Vedic Aries) is the first rashi in the Jyotish zodiac, marking the beginning of the cosmic cycle. Ruled by Mars (Mangal), Mesha natives embody pure, unfiltered yang energy — the first spark of creation that ignites all subsequent action.\n\nMesha individuals are the pioneers of the zodiac. They are drawn to beginnings: new projects, new relationships, new frontiers. Their courage is instinctive rather than calculated — they leap before others have finished assessing the gap.\n\nIn Vedic astrology, the Sun is exalted in Mesha at 10° — this is the sign where solar energy is at its absolute peak. Mesha natives often carry a solar quality about them: bright, warming, and sometimes too intense to look at directly.`,
    jyotish_tradition: `In Jyotish, Mesha is considered the rashi of action (karma) and beginnings. It corresponds to the head in Kalapurusha (the cosmic body), making Mesha natives particularly prone to headaches and scalp conditions. The rashi's ruler Mars (Mangal) governs blood, energy, and initiative. A strong Mars in the chart blesses Mesha natives with extraordinary drive; a weak or afflicted Mars can create anger, impulsiveness, and accident-proneness. Mesha is a moveable (chara) rashi — those with strong Mesha placements dislike being fixed in one place for too long.`,
    ruling_planet_detail: `Mars (Mangal) rules Mesha with fiery authority. In Vedic tradition, Mars is the planet of dharma — righteous action. The Mars mantra "Om Angarakaya Namaha" or "Om Kraam Kreem Kraum Sah Bhaumaya Namah" is traditionally recited on Tuesdays to strengthen Mars energy. Red coral (Moonga) worn on the ring finger of the right hand on a Tuesday is the traditional remedy for Mesha natives seeking to enhance Mars's blessings.`,
    lucky_gemstone: 'Red Coral (Moonga)',
    gemstone_detail: 'Red coral is the primary gemstone for Mesha Rashi, prescribed to strengthen Mars. It should be set in copper or gold, worn on the ring finger of the right hand, and activated on a Tuesday morning during the hora (planetary hour) of Mars. Natural, untreated red coral from the Mediterranean or Japanese seas is preferred.',
    favorable_days: ['Tuesday', 'Sunday'],
    ayurveda_connection: `In Ayurveda, Mesha is associated with Pitta dosha — the fire/water element governing transformation, metabolism, and digestion. Mesha natives tend toward Pitta constitution: medium build, warm body temperature, strong digestion, and a tendency toward inflammation, skin conditions, and irritability under stress. Cooling foods (cucumber, coconut, mint), avoiding excessive spicy food, and pranayama practices like Sheetali (cooling breath) are particularly beneficial.`,
    famous_people: [
      { name: 'Lady Gaga', born: 1986 }, { name: 'Mariah Carey', born: 1969 },
      { name: 'Robert Downey Jr.', born: 1965 }, { name: 'Emma Watson', born: 1990 },
      { name: 'Elton John', born: 1947 },
    ],
    strengths_detail: 'Extraordinary initiative, natural leadership that comes from genuine courage rather than ego, the ability to act decisively in crisis, and an infectious enthusiasm that energizes those around them.',
    challenges_detail: 'Impatience, a tendency to abandon projects once the initial excitement fades, difficulty with authority, and a temper that can flare suddenly. Learning to pause before acting is the Mesha native\'s greatest growth edge.',
    in_love: 'Mesha natives love passionately and pursue their beloved with great ardour. They need partners who can appreciate their intensity without feeling overwhelmed. Best matched with Simha and Dhanu — fellow fire rashis who can match Mesha\'s energy.',
    in_career: 'Military, entrepreneurship, surgery, athletics, and any field requiring decisive action under pressure. Mesha natives thrive when they have autonomy and clear opponents to overcome.',
    compatible_rashis: ['Simha', 'Dhanu', 'Mithuna', 'Kumbha'],
    faq: [
      { q: 'What is Mesha Rashi in English?', a: 'Mesha Rashi corresponds to Aries in Western astrology, though the dates differ due to the ayanamsa (precession offset) in Jyotish. Mesha in Vedic astrology spans approximately April 14 – May 14 (sidereal dates).' },
      { q: 'Which planet rules Mesha Rashi?', a: 'Mars (Mangal) rules Mesha Rashi. The Sun is exalted in Mesha at 10°, and Saturn is debilitated in Mesha — this makes the rashi a place of intense solar and martian energy.' },
      { q: 'What are the lucky colors for Mesha Rashi?', a: 'Red and orange are the primary lucky colors for Mesha Rashi, reflecting the Mars rulership. White and yellow are also favorable. Black and dark blue are generally considered inauspicious.' },
      { q: 'What gemstone should Mesha Rashi wear?', a: 'Red Coral (Moonga) is the primary gemstone for Mesha Rashi, prescribed to strengthen Mars. It should be worn on the ring finger of the right hand in copper or gold, on a Tuesday.' },
      { q: 'Is Mesha Rashi the same as Aries?', a: 'Mesha and Aries cover the same zodiac segment, but their date ranges differ. Western Aries spans roughly March 21 – April 19, while Vedic Mesha spans approximately April 14 – May 14 due to the ~24° ayanamsa correction.' },
    ],
  },
  vrishabh: {
    full_description: `Vrishabha Rashi (Vedic Taurus) is the second rashi, ruled by Venus (Shukra). If Mesha is the spark, Vrishabha is the earth that catches and sustains the flame. Vrishabha natives are the builders, the sustainers, and the refiners of the zodiac.\n\nVrishabha people possess an extraordinary sensitivity to sensory experience — they notice textures, scents, tastes, and sounds with an acuity that others lack. This makes them connoisseurs of beauty and comfort in the deepest sense.\n\nIn Vedic astrology, the Moon is exalted in Vrishabha at 3° — this is the most nourishing placement possible for the Moon, reflecting Vrishabha's fundamental quality of providing sustenance and stability.`,
    jyotish_tradition: `In Kalapurusha, Vrishabha corresponds to the face, neck, and throat — making Vrishabha natives prone to throat conditions and gifted with beautiful voices. Vrishabha is a fixed (sthira) rashi — those with strong Vrishabha placements are remarkably stubborn, persistent, and resistant to change. Venus as ruler makes this a rashi of beauty, art, music, and material enjoyment (bhoga).`,
    ruling_planet_detail: `Venus (Shukra) rules Vrishabha and is considered one of the great benefics in Vedic astrology. Shukra governs beauty, art, music, romance, luxury, and material prosperity. The Venus mantra "Om Shum Shukraya Namah" is traditionally recited on Fridays. Diamond (Heera) or white sapphire worn on the ring finger of the right hand on a Friday is the traditional remedy.`,
    lucky_gemstone: 'Diamond or White Sapphire',
    gemstone_detail: 'Diamond (Heera) is the primary gemstone for Vrishabha Rashi, prescribed to strengthen Venus. For those unable to afford diamond, white sapphire or white zircon are effective alternatives. Set in platinum or white gold, worn on the ring finger of the right hand, activated on a Friday morning.',
    favorable_days: ['Friday', 'Wednesday'],
    ayurveda_connection: `Vrishabha is associated with Kapha dosha in Ayurveda — the earth/water element governing stability, lubrication, and structure. Vrishabha natives tend toward Kapha constitution: larger frame, slow metabolism, excellent stamina, and tendency toward weight gain, congestion, and lethargy. Light, warm, spicy foods; vigorous exercise; and dry massage (udvartana) with stimulating herbs support Vrishabha health.`,
    famous_people: [
      { name: 'Adele', born: 1988 }, { name: 'Dwayne Johnson', born: 1972 },
      { name: 'Sachin Tendulkar', born: 1973 }, { name: 'Mark Zuckerberg', born: 1984 },
      { name: 'Queen Victoria', born: 1819 },
    ],
    strengths_detail: 'Extraordinary patience, practical intelligence, reliability that makes others feel genuinely secure, an innate aesthetic sense, and a determination that outlasts almost any challenge.',
    challenges_detail: 'Resistance to change, possessiveness in relationships, overindulgence in physical pleasures, and a stubbornness that can prevent important growth. Learning to release what no longer serves is essential.',
    in_love: 'Vrishabha natives are deeply sensual and loyal partners. They express love through physical affection, practical care, and the creation of beautiful shared environments. Best matched with Kanya and Makara.',
    in_career: 'Finance, banking, real estate, music, the culinary arts, fashion, and any field rewarding patience and attention to quality. Vrishabha natives excel at long-term wealth building.',
    compatible_rashis: ['Kanya', 'Makara', 'Karka', 'Meena'],
    faq: [
      { q: 'What is Vrishabha Rashi in English?', a: 'Vrishabha Rashi corresponds to Taurus in Western astrology. In Vedic astrology, Vrishabha spans approximately May 15 – June 14 (sidereal dates).' },
      { q: 'Which planet rules Vrishabha Rashi?', a: 'Venus (Shukra) rules Vrishabha Rashi. The Moon is exalted in Vrishabha at 3° — this is the most auspicious lunar placement in the entire zodiac.' },
      { q: 'What gemstone should Vrishabha Rashi wear?', a: 'Diamond (Heera) is the primary gemstone for Vrishabha Rashi. White sapphire or white zircon are effective alternatives. Worn on the ring finger of the right hand in platinum or white gold on a Friday.' },
      { q: 'Is Vrishabha Rashi compatible with Kanya?', a: 'Yes — Vrishabha and Kanya are highly compatible in Vedic astrology. Both are earth element rashis sharing Venus-Mercury compatibility, practical values, and a love of quality and refinement.' },
      { q: 'What body parts does Vrishabha Rashi rule?', a: 'Vrishabha rules the face, neck, throat, and tonsils in Kalapurusha (the cosmic body). Vrishabha natives may be prone to throat conditions but often possess naturally beautiful voices.' },
    ],
  },
  mithun: {
    full_description: `Mithuna Rashi (Vedic Gemini) is the third rashi, ruled by Mercury (Budha). Mithuna is the rashi of duality, communication, and the meeting of opposites. The symbol of the twin (Mithuna literally means "couple" or "pair") reflects the essential quality of this sign: the ability to hold two things simultaneously.\n\nMithuna natives are the most intellectually agile of all rashis. They process information with remarkable speed, see multiple sides of every question, and communicate with a fluency that can be almost magical in its effectiveness.\n\nIn Vedic astrology, Mithuna is considered an airy, mutable rashi with strong Mercury rulership — a sign of trade, communication, teaching, and the exchange of ideas.`,
    jyotish_tradition: `In Kalapurusha, Mithuna rules the shoulders, arms, and lungs. Mithuna natives may be prone to respiratory conditions and shoulder tension. Mercury as ruler makes this a rashi of buddhi (intellect), vyapara (trade/business), and lekhana (writing). Mithuna is a dual (dwiswabhava) rashi — combining elements of both moveable and fixed, allowing for remarkable adaptability.`,
    ruling_planet_detail: `Mercury (Budha) rules Mithuna and represents the analytical mind, communication, and discrimination (viveka). The Mercury mantra "Om Bum Budhaya Namah" is recited on Wednesdays. Emerald (Panna) worn on the little finger of the right hand on a Wednesday is the traditional gemstone remedy.`,
    lucky_gemstone: 'Emerald (Panna)',
    gemstone_detail: 'Emerald is the primary gemstone for Mithuna Rashi, strengthening Mercury. Colombian or Zambian emerald of good clarity is preferred. Set in gold, worn on the little finger of the right hand, activated on a Wednesday morning during Mercury hora.',
    favorable_days: ['Wednesday', 'Friday'],
    ayurveda_connection: `Mithuna is associated with a Vata-Pitta constitution in Ayurveda. The airy Mercury rulership creates Vata tendencies (anxiety, dryness, scattered energy) while the natural intelligence creates Pitta sharpness. Mithuna natives benefit from grounding practices: warm oil massage (abhyanga), regular meals at consistent times, and pranayama to calm the nervous system.`,
    famous_people: [
      { name: 'Angelina Jolie', born: 1975 }, { name: 'Johnny Depp', born: 1963 },
      { name: 'Narendra Modi', born: 1950 }, { name: 'Kanye West', born: 1977 },
      { name: 'Che Guevara', born: 1928 },
    ],
    strengths_detail: 'Exceptional communication ability, quick intelligence, remarkable adaptability, natural curiosity that makes learning effortless, and a wit that makes even difficult conversations enjoyable.',
    challenges_detail: 'Inconsistency, difficulty with sustained commitment, a tendency to skim the surface rather than dive deep, and a nervous system that requires careful management. Learning to stay when the novelty fades is essential.',
    in_love: 'Mithuna natives need mental stimulation from partners above all else. A relationship that keeps their mind engaged will keep their heart engaged. Best matched with Tula and Kumbha.',
    in_career: 'Journalism, teaching, writing, public relations, technology, trading, and any field where communication and quick thinking are valued. Mithuna natives excel at multitasking and often have multiple careers.',
    compatible_rashis: ['Tula', 'Kumbha', 'Mesha', 'Simha'],
    faq: [
      { q: 'What is Mithuna Rashi in English?', a: 'Mithuna Rashi corresponds to Gemini in Western astrology. In Vedic astrology, Mithuna spans approximately June 15 – July 16 (sidereal dates).' },
      { q: 'Which planet rules Mithuna Rashi?', a: 'Mercury (Budha) rules Mithuna Rashi. Mercury is the planet of intellect, communication, and commerce in Vedic astrology.' },
      { q: 'What gemstone should Mithuna Rashi wear?', a: 'Emerald (Panna) is the primary gemstone for Mithuna Rashi, strengthening Mercury. Worn on the little finger of the right hand in gold on a Wednesday.' },
      { q: 'What are the strengths of Mithuna Rashi?', a: 'Mithuna natives are exceptionally communicative, intellectually agile, adaptable, and naturally curious. They excel in any field requiring quick thinking and effective communication.' },
      { q: 'Which rashis are compatible with Mithuna?', a: 'Mithuna is most compatible with Tula and Kumbha (fellow air rashis) and has good compatibility with Mesha and Simha. The most challenging matches are with Dhanu and Meena.' },
    ],
  },
  kark: {
    full_description: `Karka Rashi (Vedic Cancer) is the fourth rashi, ruled by the Moon (Chandra). Karka is the rashi of the heart — of home, family, memory, and the deep emotional bonds that sustain life. If Mesha is the warrior and Vrishabha the farmer, Karka is the mother: nurturing, protective, and driven by love.\n\nKarka natives feel everything more deeply than other rashis. They have an emotional memory that is almost supernatural — they remember exactly how something felt, often long after the logical details have faded. This gift makes them extraordinary empaths, storytellers, and healers.\n\nIn Vedic astrology, the Moon is the ruler of Karka — its own house. This makes Karka natives particularly sensitive to lunar cycles, often feeling the new moon and full moon physically as well as emotionally.`,
    jyotish_tradition: `In Kalapurusha, Karka rules the chest, breasts, and stomach. Karka natives often carry emotions in the stomach — stress manifests as digestive disturbance. Karka is a moveable (chara) water rashi, making its natives highly adaptable emotionally but sometimes unstable. Jupiter is exalted in Karka at 5° — this is one of the most expansive and blessed placements in Jyotish.`,
    ruling_planet_detail: `The Moon (Chandra) rules Karka and represents mind (manas), emotions, mother, home, and the subconscious. The Moon changes signs every 2.5 days, making Karka natives particularly influenced by the moon's transits. The mantra "Om Chandraya Namah" or "Om Shram Shreem Shraum Sah Chandraya Namah" is recited on Mondays. Pearl (Moti) worn on the little finger or ring finger of the right hand on a Monday is the traditional remedy.`,
    lucky_gemstone: 'Pearl (Moti)',
    gemstone_detail: 'Natural pearl (not cultured) is the primary gemstone for Karka Rashi. South Sea or Basra pearls are considered most potent. Set in silver, worn on the little finger of the right hand, activated on a Monday evening (pearl is a lunar stone and activates best under moonlight).',
    favorable_days: ['Monday', 'Thursday'],
    ayurveda_connection: `Karka is associated with Kapha dosha in Ayurveda, with strong lunar (Water element) influence. Karka natives are prone to water retention, mucus accumulation, and emotional eating. They thrive with regular, warming meals, avoiding cold foods and drinks, and practices that support emotional processing — journaling, therapy, and time near water for grounding.`,
    famous_people: [
      { name: 'Princess Diana', born: 1961 }, { name: 'Selena Gomez', born: 1992 },
      { name: 'Tom Hanks', born: 1956 }, { name: 'Robin Williams', born: 1951 },
      { name: 'Meryl Streep', born: 1949 },
    ],
    strengths_detail: 'Profound empathy, extraordinary memory, the ability to create nurturing environments that make others feel deeply at home, intuitive intelligence that reads situations below the surface, and fierce protective loyalty.',
    challenges_detail: 'Emotional volatility, difficulty letting go of past hurts, codependency, and a tendency to withdraw into a shell when feeling threatened. Learning to process emotions without being controlled by them is essential.',
    in_love: 'Karka natives love with their whole heart and need partners who can appreciate depth of feeling without being overwhelmed by it. Security and commitment are essential. Best matched with Vrishchika and Meena.',
    in_career: 'Nursing, psychology, teaching, cooking, real estate, child care, and any field where nurturing and emotional intelligence are valued. Karka natives excel in caring professions.',
    compatible_rashis: ['Vrishchika', 'Meena', 'Vrishabha', 'Kanya'],
    faq: [
      { q: 'What is Karka Rashi in English?', a: 'Karka Rashi corresponds to Cancer in Western astrology. In Vedic astrology, Karka spans approximately July 17 – August 16 (sidereal dates).' },
      { q: 'Which planet rules Karka Rashi?', a: 'The Moon (Chandra) rules Karka Rashi. Jupiter is exalted in Karka at 5°, making this one of the most spiritually significant placements in Jyotish.' },
      { q: 'What gemstone should Karka Rashi wear?', a: 'Natural pearl (Moti) is the primary gemstone for Karka Rashi. Set in silver, worn on the little finger of the right hand on a Monday evening.' },
      { q: 'Why are Karka natives so emotional?', a: 'Karka is ruled by the Moon, the planet of the mind and emotions in Vedic astrology. The Moon changes signs every 2.5 days, making Karka natives particularly sensitive to these cycles.' },
      { q: 'What careers suit Karka Rashi?', a: 'Nursing, psychology, teaching, hospitality, real estate, food industry, and caregiving careers suit Karka natives. Their emotional intelligence and nurturing instincts are greatest professional assets.' },
    ],
  },
  simha: {
    full_description: `Simha Rashi (Vedic Leo) is the fifth rashi, ruled by the Sun (Surya). Simha is the rashi of creative self-expression, royalty, and the heart's deepest generosity. It is the only rashi in the Vedic zodiac ruled by the Sun — making it the most distinctly individual and ego-conscious of all signs.\n\nSimha natives carry a solar quality that is difficult to ignore. They have a natural authority that doesn't need to announce itself — it simply is. When a Simha walks into a room, their presence is felt before their name is known.\n\nThe lion (Simha) is the king of beasts in Indian tradition, and Simha natives share this regal quality — a combination of power, generosity, and the expectation of loyalty that defines true leadership.`,
    jyotish_tradition: `In Kalapurusha, Simha rules the heart and spine. This gives Simha natives both great vitality and vulnerability to heart and back conditions. Simha is a fixed (sthira) fire rashi — this combination of fire and fixity creates the most intensely individuated placement in the zodiac. The Sun in its own sign gives great confidence and a natural connection to dharma (righteous purpose).`,
    ruling_planet_detail: `The Sun (Surya) rules Simha and represents atma (soul), authority, father, government, and life force. The Sun is the luminary of consciousness in Vedic astrology. The Gayatri Mantra is the traditional Surya mantra. Ruby (Manikya) worn on the ring finger of the right hand, set in gold, on a Sunday is the traditional remedy for Simha natives.`,
    lucky_gemstone: 'Ruby (Manikya)',
    gemstone_detail: 'Ruby (Manikya) is the primary gemstone for Simha Rashi, strengthening the Sun. Burmese or Mozambique ruby of good colour and clarity is preferred. Set in gold, worn on the ring finger of the right hand, activated on a Sunday during Surya hora (the first hour after sunrise on Sunday).',
    favorable_days: ['Sunday', 'Tuesday'],
    ayurveda_connection: `Simha is associated with Pitta dosha in Ayurveda, with strong solar fire. Simha natives have strong digestion and metabolism but are prone to inflammation, fevers, and ego-driven stress. They benefit from cooling practices: rose water, coconut oil, moonlight walks, and avoiding excessive heat and competition.`,
    famous_people: [
      { name: 'Barack Obama', born: 1961 }, { name: 'Madonna', born: 1958 },
      { name: 'Amitabh Bachchan', born: 1942 }, { name: 'Jennifer Lopez', born: 1969 },
      { name: 'Napoleon Bonaparte', born: 1769 },
    ],
    strengths_detail: 'Natural leadership presence, extraordinary generosity, creative vision, a loyalty to those they love that is absolute, and the ability to inspire others to reach beyond their perceived limits.',
    challenges_detail: 'Pride that makes apology difficult, a need for admiration that can tip into vanity, difficulty sharing the spotlight, and a sensitivity to criticism that is at odds with their commanding exterior. Learning humility is the Simha native\'s deepest growth work.',
    in_love: 'Simha natives love dramatically and generously. They need to be admired by their partner and in turn shower them with gifts and grand gestures. Best matched with Mesha and Dhanu.',
    in_career: 'Politics, entertainment, management, entrepreneurship, teaching, and any role with visibility and creative authority. Simha natives need to be seen and appreciated in their work to thrive.',
    compatible_rashis: ['Mesha', 'Dhanu', 'Mithuna', 'Tula'],
    faq: [
      { q: 'What is Simha Rashi in English?', a: 'Simha Rashi corresponds to Leo in Western astrology. In Vedic astrology, Simha spans approximately August 17 – September 16 (sidereal dates).' },
      { q: 'Which planet rules Simha Rashi?', a: 'The Sun (Surya) rules Simha Rashi — it is the only rashi in the Vedic zodiac with a single luminary as ruler. This gives Simha natives their distinctly solar, individuated character.' },
      { q: 'What gemstone should Simha Rashi wear?', a: 'Ruby (Manikya) is the primary gemstone for Simha Rashi. Burmese or Mozambique ruby in gold, worn on the ring finger of the right hand on a Sunday.' },
      { q: 'Why are Simha Rashi natives natural leaders?', a: 'The Sun as ruler gives Simha natives a direct connection to authority, confidence, and dharma (righteous purpose). They lead through example and inspiration rather than demand.' },
      { q: 'What health issues are common for Simha Rashi?', a: 'Simha rules the heart and spine in Kalapurusha. Natives may be prone to cardiac conditions, back problems, and Pitta-driven inflammation. Regular cooling practices and stress management are essential.' },
    ],
  },
  kanya: {
    full_description: `Kanya Rashi (Vedic Virgo) is the sixth rashi, ruled by Mercury (Budha). Kanya is the rashi of discernment, service, and the relentless pursuit of perfection. If Mithuna (the other Mercury rashi) represents the gathering and exchange of information, Kanya represents the refinement and application of that information.\n\nKanya natives have an analytical intelligence that sees what others miss — patterns within patterns, the small detail that changes the entire picture. This gift makes them extraordinary diagnosticians in any field: medicine, law, editing, analysis, research.\n\nIn Vedic astrology, Mercury is both the ruler and exalted in Kanya (Mercury's exaltation point is 15° Kanya) — making this the sign where Mercury's intellectual gifts are expressed most fully and precisely.`,
    jyotish_tradition: `In Kalapurusha, Kanya rules the intestines and digestive system. Kanya natives are famously prone to digestive sensitivity — their bodies register stress through the gut with remarkable precision. Kanya is a dual (dwiswabhava) earth rashi — combining practical groundedness with the flexibility to serve different functions. Venus is debilitated in Kanya (27°) — relationships may require extra attention and conscious development for Kanya natives.`,
    ruling_planet_detail: `Mercury (Budha) rules Kanya and is exalted here. In Kanya, Mercury expresses its most discriminating, service-oriented intelligence. The mantra "Om Bum Budhaya Namah" is recited on Wednesdays. Emerald (Panna) or green tourmaline worn on the little finger of the right hand in gold on a Wednesday is the traditional remedy.`,
    lucky_gemstone: 'Emerald (Panna)',
    gemstone_detail: 'Emerald is the primary gemstone for Kanya Rashi, reinforcing Mercury\'s analytical gifts. Colombian or Zambian emerald with good clarity set in gold, worn on the little finger of the right hand, activated on a Wednesday morning.',
    favorable_days: ['Wednesday', 'Friday'],
    ayurveda_connection: `Kanya is associated with Vata dosha in Ayurveda, particularly relating to the nervous system and digestive Vata. Kanya natives tend toward anxiety, digestive sensitivity, and overthinking. They benefit greatly from regular meals, warm cooked foods, abhyanga (oil massage), and practices that quiet the analytical mind — meditation, nature walks, and limited screen time before bed.`,
    famous_people: [
      { name: 'Beyoncé', born: 1981 }, { name: 'Michael Jackson', born: 1958 },
      { name: 'Mother Teresa', born: 1910 }, { name: 'Warren Buffett', born: 1930 },
      { name: 'Stephen King', born: 1947 },
    ],
    strengths_detail: 'Extraordinary attention to detail, analytical intelligence that solves problems others cannot see, deep commitment to service, reliability, and a work ethic that is second to none.',
    challenges_detail: 'Perfectionism that prevents completion, hypercriticism of self and others, anxiety driven by the analytical mind\'s tendency to find problems everywhere, and difficulty receiving help. Learning to accept "good enough" is essential growth.',
    in_love: 'Kanya natives express love through acts of service — they show they care by taking care. They need partners who appreciate this form of devotion without demanding performative emotion. Best matched with Vrishabha and Makara.',
    in_career: 'Medicine, editing, research, accounting, nutrition, veterinary science, and any field requiring precision and service orientation. Kanya natives are the most skilled craftspeople of the zodiac.',
    compatible_rashis: ['Vrishabha', 'Makara', 'Karka', 'Vrishchika'],
    faq: [
      { q: 'What is Kanya Rashi in English?', a: 'Kanya Rashi corresponds to Virgo in Western astrology. In Vedic astrology, Kanya spans approximately September 17 – October 17 (sidereal dates).' },
      { q: 'Which planet rules Kanya Rashi?', a: 'Mercury (Budha) rules Kanya Rashi and is also exalted here at 15°. This double Mercury influence makes Kanya the most analytically precise rashi in the zodiac.' },
      { q: 'What gemstone should Kanya Rashi wear?', a: 'Emerald (Panna) is the primary gemstone for Kanya Rashi. Worn on the little finger of the right hand in gold on a Wednesday.' },
      { q: 'Why are Kanya Rashi natives so detail-oriented?', a: 'Mercury\'s rulership and exaltation in Kanya creates an analytical mind capable of perceiving extraordinarily fine distinctions. This, combined with Kanya\'s earth element, grounds this intelligence in practical application.' },
      { q: 'What health concerns are common for Kanya Rashi?', a: 'Kanya rules the intestines in Kalapurusha. Digestive sensitivity, IBS, and stress-related gut issues are common. Vata-balancing dietary and lifestyle practices are particularly important.' },
    ],
  },
  tula: {
    full_description: `Tula Rashi (Vedic Libra) is the seventh rashi, ruled by Venus (Shukra). Tula is the rashi of relationship, balance, and the deep human need for harmony with others. The scales (Tula literally means "balance") represent not just fairness but the ongoing, dynamic process of finding equilibrium.\n\nTula natives have an exceptional gift for seeing all sides of a situation — a quality that makes them natural diplomats and mediators, but sometimes prevents them from taking decisive action. Their desire for fairness is genuine and deep: they are genuinely uncomfortable when they perceive injustice.\n\nIn Vedic astrology, Saturn is exalted in Tula at 20° — this placement of Saturn in the rashi of balance suggests that disciplined, just action (the highest qualities of both Saturn and Tula) brings the greatest rewards.`,
    jyotish_tradition: `In Kalapurusha, Tula rules the kidneys and lower back. Tula natives may be prone to kidney conditions and lower back issues, often exacerbated by indecision and relationship stress. Tula is a moveable (chara) air rashi — making its natives social, adaptable, and naturally inclined toward partnership. The Sun is debilitated in Tula (10°) — Tula natives may need to consciously develop self-confidence and individual identity.`,
    ruling_planet_detail: `Venus (Shukra) rules Tula, making this the sign of beauty in relationship rather than beauty in the material world (as in Vrishabha). The mantra "Om Shum Shukraya Namah" is recited on Fridays. Diamond or white sapphire worn on the ring finger of the right hand in white gold or platinum on a Friday is the traditional remedy.`,
    lucky_gemstone: 'Diamond or White Sapphire',
    gemstone_detail: 'Diamond is the primary gemstone for Tula Rashi. For those unable to afford diamond, white sapphire or opal are effective alternatives. Set in platinum or white gold, worn on the ring finger of the right hand, activated on a Friday morning.',
    favorable_days: ['Friday', 'Saturday'],
    ayurveda_connection: `Tula is associated with Vata-Pitta constitution in Ayurveda, with the airy Venus quality creating aesthetic sensitivity and social Vata. Tula natives benefit from regular routine (to combat Vata irregularity), beautiful environments, and social connection for their emotional health. The kidneys respond well to adequate hydration and reducing excessive Pitta foods.`,
    famous_people: [
      { name: 'Mahatma Gandhi', born: 1869 }, { name: 'Amitabh Bachchan', born: 1942 },
      { name: 'Kim Kardashian', born: 1980 }, { name: 'Will Smith', born: 1968 },
      { name: 'John Lennon', born: 1940 },
    ],
    strengths_detail: 'Natural diplomatic intelligence, a genuine commitment to fairness, exceptional aesthetic sense, the ability to see all sides of a situation, and a social grace that makes everyone feel valued.',
    challenges_detail: 'Chronic indecision, people-pleasing at the cost of authentic self-expression, difficulty with conflict, and a tendency to avoid difficult conversations until the situation becomes a crisis.',
    in_love: 'Tula natives are among the most romantic signs in the zodiac. They create beautiful relationship experiences and genuinely need partnership to feel complete. Best matched with Mithuna and Kumbha.',
    in_career: 'Law, diplomacy, design, fashion, public relations, and any role requiring fairness, aesthetic judgment, and social intelligence. Tula natives excel at negotiation and creating consensus.',
    compatible_rashis: ['Mithuna', 'Kumbha', 'Simha', 'Dhanu'],
    faq: [
      { q: 'What is Tula Rashi in English?', a: 'Tula Rashi corresponds to Libra in Western astrology. In Vedic astrology, Tula spans approximately October 18 – November 16 (sidereal dates).' },
      { q: 'Which planet rules Tula Rashi?', a: 'Venus (Shukra) rules Tula Rashi. Saturn is exalted in Tula at 20°, and the Sun is debilitated in Tula at 10° — making this a rashi of complex social and spiritual energies.' },
      { q: 'What gemstone should Tula Rashi wear?', a: 'Diamond is the primary gemstone for Tula Rashi. White sapphire or opal are alternatives. Worn on the ring finger of the right hand in platinum on a Friday.' },
      { q: 'Why are Tula Rashi natives so indecisive?', a: 'The scales of Tula represent constant weighing of options — a genuine desire for the most fair and balanced choice. This gift for seeing all sides can create paralysis when quick decisions are needed.' },
      { q: 'Is Tula Rashi compatible with Mesha?', a: 'Tula and Mesha are opposing rashis in the Vedic zodiac — often a challenging but deeply transformative match. The opposition creates magnetic attraction but requires mutual respect of very different natures.' },
    ],
  },
  vrishchik: {
    full_description: `Vrishchika Rashi (Vedic Scorpio) is the eighth rashi, ruled by Mars (Mangal) in classical Jyotish (with Ketu as co-ruler in some traditions). Vrishchika is the rashi of depth, transformation, and the hidden dimensions of existence — the most mysterious and psychologically complex rashi in the Vedic zodiac.\n\nVrishchika natives are drawn to what is hidden, forbidden, or difficult. They are natural investigators — not merely curious but compelled to understand what lies beneath the surface of any situation, any person, any mystery. Their perception operates at frequencies most others cannot access.\n\nIn Vedic astrology, Vrishchika rules the eighth house principle: longevity, death and rebirth, the occult, and radical transformation. Natives with strong Vrishchika placements often experience profound life changes that would break others but instead forge them into something stronger.`,
    jyotish_tradition: `In Kalapurusha, Vrishchika rules the reproductive organs and elimination system. This gives Vrishchika natives a deep connection to life-force (ojas) and its preservation. Vrishchika is a fixed (sthira) water rashi — combining the depth of water with the intensity of fixed energy creates extraordinary emotional endurance and the potential for obsession. The Moon is debilitated in Vrishchika (3°) — emotional life may be turbulent and require conscious management.`,
    ruling_planet_detail: `Mars (Mangal) rules Vrishchika in classical Jyotish, expressing Mars energy in its most interior, investigative, and transformative form — quite different from Mesha's outward martial energy. Ketu (the south node) is the co-ruler in many modern Jyotish traditions, adding an element of past-life karma and spiritual intensity. Red coral (Moonga) is the traditional gemstone, supplemented by cat's eye (Lahsuniya) for Ketu.`,
    lucky_gemstone: 'Red Coral (Moonga)',
    gemstone_detail: 'Red coral (Moonga) strengthens Mars for Vrishchika Rashi natives. Cat\'s eye (Lahsuniya) may be added to strengthen Ketu if the Ketu is significant in the chart. Red coral set in copper or gold, worn on the ring finger of the right hand on a Tuesday.',
    favorable_days: ['Tuesday', 'Monday'],
    ayurveda_connection: `Vrishchika is associated with Pitta-Kapha constitution in Ayurveda, with the fixed water quality creating great emotional depth and potential for stagnation. Vrishchika natives benefit from practices that facilitate emotional release: vigorous exercise, swimming, and journaling. Avoiding suppression of emotions is particularly important for long-term health.`,
    famous_people: [
      { name: 'Shah Rukh Khan', born: 1965 }, { name: 'Leonardo DiCaprio', born: 1974 },
      { name: 'Bill Gates', born: 1955 }, { name: 'Marie Curie', born: 1867 },
      { name: 'Pablo Picasso', born: 1881 },
    ],
    strengths_detail: 'Penetrating psychological insight, extraordinary emotional depth, the ability to endure and transform through crisis, fierce loyalty to those who have earned it, and a magnetic personal power that is almost impossible to ignore.',
    challenges_detail: 'Intensity that can become obsession, difficulty forgiving, jealousy and possessiveness in relationships, and a tendency toward psychological manipulation when threatened. Learning to trust the process of letting go is the Vrishchika native\'s most important work.',
    in_love: 'Vrishchika natives love with the whole of their being — completely, intensely, and permanently. They need partners who can meet their depth without retreating from it. Best matched with Karka and Meena.',
    in_career: 'Psychology, surgery, research, detective work, financial investigation, occult sciences, and any field requiring depth of understanding and willingness to go where others fear. Vrishchika natives excel in fields where transformation is the purpose.',
    compatible_rashis: ['Karka', 'Meena', 'Kanya', 'Makara'],
    faq: [
      { q: 'What is Vrishchika Rashi in English?', a: 'Vrishchika Rashi corresponds to Scorpio in Western astrology. In Vedic astrology, Vrishchika spans approximately November 17 – December 15 (sidereal dates).' },
      { q: 'Which planet rules Vrishchika Rashi?', a: 'Mars (Mangal) rules Vrishchika Rashi in classical Jyotish. Ketu is the co-ruler in many modern traditions. The Moon is debilitated in Vrishchika at 3°.' },
      { q: 'What gemstone should Vrishchika Rashi wear?', a: 'Red coral (Moonga) is the primary gemstone for Vrishchika Rashi, strengthening Mars. Cat\'s eye (Lahsuniya) may be added for Ketu energy.' },
      { q: 'Why are Vrishchika Rashi natives so intense?', a: 'The combination of Mars\'s fire, Ketu\'s karmic depth, and the fixed water element creates extraordinary emotional and psychological intensity. This is the rashi most associated with transformation — including painful transformation.' },
      { q: 'What careers suit Vrishchika Rashi?', a: 'Psychology, surgery, research, intelligence work, financial analysis, and occult sciences suit Vrishchika natives. Their ability to penetrate beneath the surface is their greatest professional asset.' },
    ],
  },
  dhanu: {
    full_description: `Dhanu Rashi (Vedic Sagittarius) is the ninth rashi, ruled by Jupiter (Guru/Brihaspati). Dhanu is the rashi of wisdom, philosophy, and the great adventure of seeking truth. The archer (Dhanu means "bow") aims his arrow at the horizon — always reaching for what is beyond the immediately known.\n\nDhanu natives are the philosophers, the travellers, and the teachers of the Vedic zodiac. They have an innate faith in the goodness of existence — an optimism that, at its best, is infectious and inspiring. At its most challenging, this optimism can tip into naivety or excess.\n\nIn Vedic astrology, the ninth house (which Dhanu naturally rules) is the house of dharma, higher education, long-distance travel, spiritual teachers, and divine grace. Dhanu natives often feel divinely guided — and this faith in a larger purpose gives them remarkable courage.`,
    jyotish_tradition: `In Kalapurusha, Dhanu rules the thighs and hips — the anatomical seat of locomotion and forward movement. This gives Dhanu natives a deep physical and symbolic need to move forward, to explore. Dhanu is a dual (dwiswabhava) fire rashi — combining fire's inspiration with the flexibility to teach and explore different domains. Jupiter in Dhanu (its own sign) gives tremendous expansiveness and spiritual optimism.`,
    ruling_planet_detail: `Jupiter (Guru/Brihaspati) rules Dhanu and represents wisdom, dharma, children, spiritual teachers, and divine grace. Jupiter is the greatest benefic in Vedic astrology. The mantra "Om Brim Brihaspataye Namah" or "Om Gram Greem Graum Sah Gurave Namah" is recited on Thursdays. Yellow sapphire (Pukhraj) worn on the index finger of the right hand in gold on a Thursday is the traditional remedy.`,
    lucky_gemstone: 'Yellow Sapphire (Pukhraj)',
    gemstone_detail: 'Yellow sapphire (Pukhraj) is the primary gemstone for Dhanu Rashi, strengthening Jupiter. Sri Lankan or Burmese yellow sapphire of good clarity and vibrant color is preferred. Set in gold, worn on the index finger of the right hand, activated on a Thursday morning during Jupiter hora.',
    favorable_days: ['Thursday', 'Tuesday'],
    ayurveda_connection: `Dhanu is associated with Pitta-Vata constitution in Ayurveda. Jupiter's expansive quality combined with fire creates optimism but also excess (overindulgence in food, philosophical debate, or travel). Dhanu natives benefit from moderation, grounding practices, and care of the liver (Jupiter's organ) through avoiding excessive alcohol, fatty foods, and overexertion.`,
    famous_people: [
      { name: 'Taylor Swift', born: 1989 }, { name: 'Winston Churchill', born: 1874 },
      { name: 'Jimi Hendrix', born: 1942 }, { name: 'Walt Disney', born: 1901 },
      { name: 'Swami Vivekananda', born: 1863 },
    ],
    strengths_detail: 'Philosophical wisdom, genuine optimism that lifts those around them, adventurousness, a love of learning and teaching, and a directness and honesty that, while sometimes blunt, is always trustworthy.',
    challenges_detail: 'Excess in all forms, commitment-phobia, bluntness that wounds unintentionally, and a restlessness that prevents them from staying with things long enough to reach the depth their intelligence is capable of.',
    in_love: 'Dhanu natives need partners who share their love of freedom and exploration. Possessiveness is fatal to a Dhanu relationship. Best matched with Mesha and Simha — fellow fire rashis.',
    in_career: 'Philosophy, law, higher education, international business, publishing, travel, and spiritual teaching. Dhanu natives are natural professors and advisors who excel when their wisdom is sought.',
    compatible_rashis: ['Mesha', 'Simha', 'Tula', 'Kumbha'],
    faq: [
      { q: 'What is Dhanu Rashi in English?', a: 'Dhanu Rashi corresponds to Sagittarius in Western astrology. In Vedic astrology, Dhanu spans approximately December 16 – January 14 (sidereal dates).' },
      { q: 'Which planet rules Dhanu Rashi?', a: 'Jupiter (Guru/Brihaspati) rules Dhanu Rashi. This makes Dhanu natives naturally philosophical, optimistic, and drawn to wisdom traditions.' },
      { q: 'What gemstone should Dhanu Rashi wear?', a: 'Yellow sapphire (Pukhraj) is the primary gemstone for Dhanu Rashi. Set in gold, worn on the index finger of the right hand on a Thursday morning.' },
      { q: 'Why are Dhanu Rashi natives so philosophical?', a: 'Jupiter\'s rulership gives Dhanu natives a natural orientation toward wisdom, meaning, and the big questions of existence. The ninth rashi naturally connects to dharma, higher education, and spiritual seeking.' },
      { q: 'What careers suit Dhanu Rashi?', a: 'Higher education, law, philosophy, international business, publishing, and spiritual teaching suit Dhanu natives. Their wisdom and natural teaching ability are their greatest professional gifts.' },
    ],
  },
  makar: {
    full_description: `Makara Rashi (Vedic Capricorn) is the tenth rashi, ruled by Saturn (Shani). Makara is the rashi of achievement, discipline, and the patient, methodical climb toward mastery. If Dhanu is the visionary, Makara is the architect who turns vision into reality through sustained effort.\n\nMakara natives are the most disciplined achievers in the Vedic zodiac. They have a relationship with time that other signs lack — they understand that extraordinary outcomes require extraordinary patience, and they are willing to give that patience without resentment.\n\nIn Vedic astrology, Mars is exalted in Makara at 28° — this placement of the planet of action in the rashi of disciplined ambition creates the most effective and strategically brilliant form of energy expression.`,
    jyotish_tradition: `In Kalapurusha, Makara rules the knees and joints. Makara natives often experience knee and joint issues, particularly later in life — the physical manifestation of Saturn's association with age and limitation. Makara is a moveable (chara) earth rashi — despite its reputation for conservatism, Makara natives are willing to move and change strategically when the long-term outcome justifies it.`,
    ruling_planet_detail: `Saturn (Shani) rules Makara and represents discipline, karma, longevity, service, and the lessons of time. Saturn is simultaneously the most feared and most respected planet in Vedic astrology — its lessons are hard but its rewards are lasting. The mantra "Om Sham Shanaischaraya Namah" is recited on Saturdays. Blue sapphire (Neelam) worn on the middle finger of the right hand in silver or five-metal alloy (panchaloha) on a Saturday is the traditional remedy.`,
    lucky_gemstone: 'Blue Sapphire (Neelam)',
    gemstone_detail: 'Blue sapphire (Neelam) is one of the most powerful and fastest-acting gemstones in Vedic astrology. Its effects are said to be felt within days of wearing. It must be worn only after astrological consultation. Set in silver or panchaloha, worn on the middle finger of the right hand on a Saturday.',
    favorable_days: ['Saturday', 'Wednesday'],
    ayurveda_connection: `Makara is associated with Vata dosha in Ayurveda, with Saturn's cold, dry, contracting quality. Makara natives tend toward dryness (skin, joints, digestive tract) and rigidity. They benefit from warming, oily, nourishing foods; warm oil massage (abhyanga); and keeping the joints warm, especially in cold weather.`,
    famous_people: [
      { name: 'Narendra Modi', born: 1950 }, { name: 'Muhammad Ali', born: 1942 },
      { name: 'Denzel Washington', born: 1954 }, { name: 'Deepak Chopra', born: 1946 },
      { name: 'Isaac Newton', born: 1643 },
    ],
    strengths_detail: 'Extraordinary discipline and patience, strategic intelligence that calculates outcomes across long time horizons, reliability that others can build upon, perseverance that outlasts almost any obstacle, and a deep sense of responsibility.',
    challenges_detail: 'Excessive seriousness, difficulty enjoying the present moment, fear of failure that prevents risk-taking, a tendency toward workaholism, and emotional coldness that can make intimate connection difficult. Learning to play is the Makara native\'s essential growth work.',
    in_love: 'Makara natives show love through reliability, practical support, and absolute commitment once they have decided. They need partners who respect their ambition and don\'t take their reserve personally. Best matched with Vrishabha and Kanya.',
    in_career: 'Business, government, engineering, management, finance, and any field where long-term strategic thinking and consistent execution are rewarded. Makara natives are the natural CEOs and builders of the zodiac.',
    compatible_rashis: ['Vrishabha', 'Kanya', 'Vrishchika', 'Meena'],
    faq: [
      { q: 'What is Makara Rashi in English?', a: 'Makara Rashi corresponds to Capricorn in Western astrology. In Vedic astrology, Makara spans approximately January 15 – February 12 (sidereal dates).' },
      { q: 'Which planet rules Makara Rashi?', a: 'Saturn (Shani) rules Makara Rashi. Mars is exalted in Makara at 28° — creating the most effective combination of disciplined ambition and decisive action.' },
      { q: 'What gemstone should Makara Rashi wear?', a: 'Blue sapphire (Neelam) is the primary gemstone for Makara Rashi. It is powerful and fast-acting — must be worn only after proper astrological consultation.' },
      { q: 'Why are Makara Rashi natives so ambitious?', a: 'Saturn\'s rulership gives Makara natives a deep understanding that worthwhile achievements require sustained effort over time. They are motivated by legacy and the desire to build something lasting.' },
      { q: 'What careers suit Makara Rashi?', a: 'Business management, government, engineering, finance, and fields requiring long-term strategic planning suit Makara natives. Their patience, discipline, and strategic intelligence are their greatest professional assets.' },
    ],
  },
  kumbh: {
    full_description: `Kumbha Rashi (Vedic Aquarius) is the eleventh rashi, ruled by Saturn (Shani). Kumbha is the rashi of humanity — of the collective, the community, the great network of human connection that transcends individual self-interest. The water-bearer (Kumbha means "pot" or "vessel") pours forth not water but the nourishing fluid of wisdom and social vision.\n\nKumbha natives are the reformers, the visionaries, and the community builders of the Vedic zodiac. They see what society could be — what it should be — and feel a genuine calling to work toward that better future.\n\nIn Vedic astrology, Kumbha represents the eleventh house principle: social networks, collective goals, and the fulfillment that comes from contributing to something larger than oneself.`,
    jyotish_tradition: `In Kalapurusha, Kumbha rules the calves and ankles. Kumbha natives may be prone to circulatory issues in the lower legs. Kumbha is a fixed (sthira) air rashi — combining Saturn's structure with the air element's social and intellectual reach creates a rare combination of principled idealism and the practical ability to organize collective effort. Saturn in its own sign here gives Kumbha natives an almost paradoxical quality: both radical visionaries and disciplined pragmatists.`,
    ruling_planet_detail: `Saturn (Shani) rules Kumbha, here expressing the more collective, social, and humanitarian aspects of Saturn's energy — service to the many rather than the disciplined personal achievement of Makara. The same mantra and remedies apply as for Makara. Blue sapphire (Neelam) worn on the middle finger of the right hand in silver on a Saturday after astrological consultation.`,
    lucky_gemstone: 'Blue Sapphire (Neelam)',
    gemstone_detail: 'Blue sapphire (Neelam) is the primary gemstone for Kumbha Rashi, strengthening Saturn. Set in silver, worn on the middle finger of the right hand on a Saturday. Consultation with a qualified Jyotishi is recommended before wearing, as Neelam\'s effects are powerful and immediate.',
    favorable_days: ['Saturday', 'Sunday'],
    ayurveda_connection: `Kumbha is associated with Vata dosha with strong Saturn influence. Kumbha natives tend toward irregular routines, which exacerbates Vata. They benefit from consistent daily routine (dinacharya), warm and grounding foods, and social connection for emotional health — isolation is particularly damaging for the most socially oriented rashi.`,
    famous_people: [
      { name: 'Oprah Winfrey', born: 1954 }, { name: 'Charles Darwin', born: 1809 },
      { name: 'Abraham Lincoln', born: 1809 }, { name: 'Thomas Edison', born: 1847 },
      { name: 'Rosa Parks', born: 1913 },
    ],
    strengths_detail: 'Visionary social intelligence, genuine humanitarian impulse, the ability to inspire collective action, intellectual originality, and a personal integrity that makes them trustworthy advocates for change.',
    challenges_detail: 'Emotional detachment, dogmatic attachment to ideals, difficulty with intimate one-on-one connection, and a tendency to prioritize abstract principles over the feelings of specific individuals. Learning to care for the person in front of them as much as humanity in the abstract is essential.',
    in_love: 'Kumbha natives need intellectual and ideological compatibility above romantic chemistry. They are devoted partners who need freedom and respect for their humanitarian commitments. Best matched with Mithuna and Tula.',
    in_career: 'Social activism, technology, science, politics, community organization, and any field where systemic change is the goal. Kumbha natives are most effective when working for collective rather than individual benefit.',
    compatible_rashis: ['Mithuna', 'Tula', 'Mesha', 'Dhanu'],
    faq: [
      { q: 'What is Kumbha Rashi in English?', a: 'Kumbha Rashi corresponds to Aquarius in Western astrology. In Vedic astrology, Kumbha spans approximately February 13 – March 14 (sidereal dates).' },
      { q: 'Which planet rules Kumbha Rashi?', a: 'Saturn (Shani) rules Kumbha Rashi. In Kumbha, Saturn expresses its most humanitarian and collective qualities.' },
      { q: 'What gemstone should Kumbha Rashi wear?', a: 'Blue sapphire (Neelam) is the primary gemstone for Kumbha Rashi. Consultation with a Jyotishi is recommended before wearing.' },
      { q: 'Why are Kumbha Rashi natives so idealistic?', a: 'Saturn\'s rulership gives Kumbha natives a strong sense of social justice and collective responsibility. The fixed air quality creates principled, persistent commitment to their ideals.' },
      { q: 'What careers suit Kumbha Rashi?', a: 'Social activism, technology, political reform, scientific research, and community organizing suit Kumbha natives. Their ability to hold a vision for systemic change and organize collective effort is their greatest professional gift.' },
    ],
  },
  meen: {
    full_description: `Meena Rashi (Vedic Pisces) is the twelfth and final rashi, ruled by Jupiter (Guru/Brihaspati). Meena is the rashi of dissolution, compassion, and the return to the ocean of undifferentiated consciousness from which all creation emerged. The two fish swimming in opposite directions — one toward liberation, one toward the world — perfectly capture the Meena native's essential tension.\n\nMeena natives are the most spiritually attuned of all rashis. They feel the oneness of all things not as an intellectual concept but as a lived experience — the boundary between self and other is more permeable for them than for any other sign.\n\nIn Vedic astrology, Venus is exalted in Meena at 27° — the most refined and spiritualized expression of love and beauty, transcending personal romance toward universal compassion.`,
    jyotish_tradition: `In Kalapurusha, Meena rules the feet — the part of the body that touches the earth and also the part through which we walk the path of life. Meena natives are prone to foot conditions and are advised to protect their feet as a spiritual practice. Meena is a dual (dwiswabhava) water rashi — the most fluid and receptive of all rashi qualities. Mercury is debilitated in Meena (15°) — Meena natives may need to consciously develop practical, analytical thinking.`,
    ruling_planet_detail: `Jupiter (Guru/Brihaspati) rules Meena, here expressing the most compassionate, spiritualized, and transcendent qualities of Jupiter's wisdom — quite different from Dhanu's philosophical seeking. The mantra "Om Brim Brihaspataye Namah" is recited on Thursdays. Yellow sapphire (Pukhraj) or yellow topaz worn on the index finger of the right hand in gold on a Thursday is the traditional remedy.`,
    lucky_gemstone: 'Yellow Sapphire (Pukhraj)',
    gemstone_detail: 'Yellow sapphire (Pukhraj) is the primary gemstone for Meena Rashi, strengthening Jupiter. Sri Lankan or Burmese yellow sapphire in gold, worn on the index finger of the right hand, activated on a Thursday morning during Jupiter hora.',
    favorable_days: ['Thursday', 'Monday'],
    ayurveda_connection: `Meena is associated with Kapha-Vata constitution in Ayurveda. The water element creates emotional depth and susceptibility to absorbing others' energies. Meena natives particularly need energetic protection practices — maintaining clear personal boundaries, spending time in nature, and limiting exposure to distressing media and environments. Regular grounding through physical activity is important.`,
    famous_people: [
      { name: 'Albert Einstein', born: 1879 }, { name: 'Steve Jobs', born: 1955 },
      { name: 'Rihanna', born: 1988 }, { name: 'Kurt Cobain', born: 1967 },
      { name: 'Paramahansa Yogananda', born: 1893 },
    ],
    strengths_detail: 'Profound empathy and compassion, spiritual sensitivity and intuition, extraordinary artistic and musical gifts, the ability to see beauty in all things, and a selfless generosity that springs from genuine love of humanity.',
    challenges_detail: 'Difficulty maintaining boundaries, escapist tendencies (including substance vulnerability), being overwhelmed by others\' emotions, impracticality, and a tendency toward self-sacrifice that can tip into martyrdom. Learning to maintain clear energetic boundaries is the Meena native\'s most important practical skill.',
    in_love: 'Meena natives love with transcendent devotion — they idealize their partner and give completely. They need partners who appreciate their spiritual depth and protect them from the world\'s harshness. Best matched with Karka and Vrishchika.',
    in_career: 'The arts, music, spirituality, healing, social work, photography, and any field where empathy and creative vision are the primary tools. Meena natives are most fulfilled when their work is in service of a spiritual or humanitarian purpose.',
    compatible_rashis: ['Karka', 'Vrishchika', 'Vrishabha', 'Makara'],
    faq: [
      { q: 'What is Meena Rashi in English?', a: 'Meena Rashi corresponds to Pisces in Western astrology. In Vedic astrology, Meena spans approximately March 15 – April 13 (sidereal dates).' },
      { q: 'Which planet rules Meena Rashi?', a: 'Jupiter (Guru/Brihaspati) rules Meena Rashi. Venus is exalted in Meena at 27°, making this the rashi of transcendent love and beauty.' },
      { q: 'What gemstone should Meena Rashi wear?', a: 'Yellow sapphire (Pukhraj) is the primary gemstone for Meena Rashi. Set in gold, worn on the index finger of the right hand on a Thursday morning.' },
      { q: 'Why are Meena Rashi natives so spiritual?', a: 'Jupiter\'s rulership, the dual water quality, and the twelfth house association make Meena the most spiritually oriented rashi. The boundary between individual self and universal consciousness is naturally thinner for Meena natives.' },
      { q: 'What careers suit Meena Rashi?', a: 'The arts, music, healing, spiritual teaching, social work, and fields requiring empathy and creative imagination suit Meena natives. Their spiritual sensitivity and compassion are their most powerful professional gifts.' },
    ],
  },
};
