/**
 * Free Kundli PDF HTML (Growth P2, P2-6). Builds a clean, self-contained A4
 * page from the /api/kundali response — birth summary, planet table, current
 * Dasha and any doshas — for the browser print dialog (printHtmlViaIframe).
 * Free (the Kundli itself is free). No external assets, no user data stored.
 */
interface KundaliPdfData {
  lagna?: { sign?: string };
  rashi?: string;
  nakshatra?: { nakshatra?: string; pada?: number };
  dasha?: { mahadasha?: string; antardasha?: string };
  planets?: Array<{ name: string; sign: string; house: number; longitude: number; retrograde?: boolean }>;
  doshas?: {
    mangalDosha?: { hasDosha?: boolean; severityLabel?: string };
    kaalSarp?: { present?: boolean; type?: string | null };
    sadeSati?: { active?: boolean; phase?: string | null };
  };
}

const esc = (s: unknown) => String(s ?? '').replace(/[&<>]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;' }[c] as string));

export function buildKundaliPdfHtml(data: KundaliPdfData, meta?: { name?: string; dob?: string; place?: string }): string {
  const planetRows = (data.planets || []).map(p =>
    `<tr><td>${esc(p.name)}${p.retrograde ? ' (R)' : ''}</td><td>${esc(p.sign)}</td><td>${esc(p.house)}</td><td>${(p.longitude % 30).toFixed(1)}°</td></tr>`
  ).join('');

  const doshaBits: string[] = [];
  if (data.doshas?.mangalDosha) doshaBits.push(`Manglik: ${data.doshas.mangalDosha.hasDosha ? `present${data.doshas.mangalDosha.severityLabel ? ` (${esc(data.doshas.mangalDosha.severityLabel)})` : ''}` : 'not present'}`);
  if (data.doshas?.kaalSarp) doshaBits.push(`Kaal Sarp: ${data.doshas.kaalSarp.present ? `present${data.doshas.kaalSarp.type ? ` (${esc(data.doshas.kaalSarp.type)})` : ''}` : 'not present'}`);
  if (data.doshas?.sadeSati) doshaBits.push(`Sade Sati: ${data.doshas.sadeSati.active ? `active${data.doshas.sadeSati.phase ? ` (${esc(data.doshas.sadeSati.phase)})` : ''}` : 'not active'}`);

  return `<!doctype html><html><head><meta charset="utf-8"><title>Kundli — BornClock</title>
<style>
  @page { size: A4; margin: 16mm; }
  * { box-sizing: border-box; }
  body { font-family: Georgia, 'Times New Roman', serif; color: #0E2238; margin: 0; }
  h1 { font-size: 22px; margin: 0 0 2px; }
  .muted { color: #6b7280; font-size: 12px; }
  .section { margin-top: 18px; }
  .section h2 { font-size: 14px; border-bottom: 1px solid #e5e7eb; padding-bottom: 4px; margin: 0 0 8px; }
  table { width: 100%; border-collapse: collapse; font-size: 12px; }
  th, td { text-align: left; padding: 5px 6px; border-bottom: 1px solid #eee; }
  th { color: #6E5AA6; }
  .summary { display: flex; flex-wrap: wrap; gap: 16px; font-size: 13px; }
  .summary div span { display: block; color: #6b7280; font-size: 11px; }
  .foot { margin-top: 24px; font-size: 10px; color: #9ca3af; border-top: 1px solid #e5e7eb; padding-top: 8px; }
</style></head><body>
  <h1>Vedic Kundli</h1>
  <div class="muted">${esc(meta?.name || 'Birth chart')}${meta?.dob ? ` · ${esc(meta.dob)}` : ''}${meta?.place ? ` · ${esc(meta.place)}` : ''} · Generated by BornClock</div>

  <div class="section">
    <h2>Birth summary</h2>
    <div class="summary">
      <div><span>Lagna (Ascendant)</span>${esc(data.lagna?.sign || '—')}</div>
      <div><span>Rashi (Moon sign)</span>${esc(data.rashi || '—')}</div>
      <div><span>Nakshatra</span>${esc(data.nakshatra?.nakshatra || '—')}${data.nakshatra?.pada ? ` · Pada ${esc(data.nakshatra.pada)}` : ''}</div>
      ${data.dasha ? `<div><span>Current Dasha</span>${esc(data.dasha.mahadasha || '—')} / ${esc(data.dasha.antardasha || '—')}</div>` : ''}
    </div>
  </div>

  <div class="section">
    <h2>Planetary positions</h2>
    <table><thead><tr><th>Planet</th><th>Sign</th><th>House</th><th>Degrees</th></tr></thead>
    <tbody>${planetRows || '<tr><td colspan="4">—</td></tr>'}</tbody></table>
  </div>

  ${doshaBits.length ? `<div class="section"><h2>Doshas</h2><p style="font-size:12px;">${doshaBits.join(' · ')}</p></div>` : ''}

  <div class="foot">
    Computed with the Lahiri (sidereal) ayanamsa. This is a traditional Vedic reading for reflection, not a prediction of specific events. For the full interactive chart, dasha deep-dive and readings, visit bornclock.
  </div>
</body></html>`;
}
