// One-off: extract the shared design-system CSS from the finalized reference mockups
// and emit a SCOPED stylesheet (every selector prefixed under `.paj`) so the generic
// class names (.section/.btn/.field/.hero/.feature…) cannot leak into the other ~120
// site pages. The CSS block is identical across all four reference files, so vedic-final
// is used as the single source. Per-category accent overrides are appended at the end.
import { readFileSync, writeFileSync } from 'node:fs';

const src = readFileSync('docs/design-reference/vedic-final.html', 'utf8');
const css = src.slice(src.indexOf('<style>') + 7, src.indexOf('</style>'));

// Split a CSS string into top-level blocks by brace matching.
function splitBlocks(s) {
  const blocks = [];
  let depth = 0, start = 0;
  for (let i = 0; i < s.length; i++) {
    const ch = s[i];
    if (ch === '{') depth++;
    else if (ch === '}') {
      depth--;
      if (depth === 0) { blocks.push(s.slice(start, i + 1)); start = i + 1; }
    }
  }
  const tail = s.slice(start).trim();
  if (tail) blocks.push(tail);
  return blocks;
}

function prefixSelector(sel) {
  sel = sel.trim();
  if (!sel) return sel;
  if (sel === ':root' || sel === 'body' || sel === 'html') return '.paj';
  if (sel.startsWith('body')) return '.paj' + sel.slice(4);
  if (sel.startsWith('html')) return '.paj' + sel.slice(4);
  if (sel === '*') return '.paj *';
  if (sel.startsWith('*')) return '.paj ' + sel;
  // The four design-variant classes (editorial/atlas/field-guide/workbench) live on the SAME
  // element as .paj (<div class="paj editorial">), not as a descendant — so they must attach
  // with NO space. Scoping them as a descendant ("\.paj .editorial") silently broke every
  // variant-specific layout rule (the editorial 2-col hero collapsed to a stacked white panel).
  for (const v of ['.editorial', '.atlas', '.field-guide', '.workbench']) {
    if (sel === v || sel.startsWith(v + ' ') || sel.startsWith(v + '.') || sel.startsWith(v + '[') || sel.startsWith(v + ':')) {
      return '.paj' + sel;
    }
  }
  return '.paj ' + sel;
}

// Process a flat list of plain rules (no nested at-rules).
function processRules(body) {
  return splitBlocks(body).map(block => {
    const open = block.indexOf('{');
    if (open === -1) return block;
    const selectors = block.slice(0, open);
    const rest = block.slice(open);
    const scoped = selectors.split(',').map(prefixSelector).join(',');
    return scoped + rest;
  }).join('\n');
}

const out = [];
for (const block of splitBlocks(css)) {
  const b = block.trim();
  if (!b) continue;
  if (b.startsWith('@keyframes')) { out.push(b); continue; }
  if (b.startsWith('@media') || b.startsWith('@supports')) {
    const open = b.indexOf('{');
    const prelude = b.slice(0, open);
    const inner = b.slice(open + 1, b.lastIndexOf('}'));
    out.push(prelude + '{\n' + processRules(inner) + '\n}');
    continue;
  }
  // plain rule
  const open = b.indexOf('{');
  if (open === -1) { out.push(b); continue; }
  const selectors = b.slice(0, open);
  const rest = b.slice(open);
  out.push(selectors.split(',').map(prefixSelector).join(',') + rest);
}

const header = `/* AUTO-GENERATED by scripts/build-paj-css.mjs — Part AJ four-page redesign design system.
 * Source: docs/design-reference/vedic-final.html <style> (identical across all four refs).
 * Every selector is scoped under .paj so it cannot affect the rest of the site.
 * Per-category accent + background overrides are appended below the generated block. */\n`;

const overrides = `
/* ── Per-category theme overrides (accent + science background) ───────────── */
.paj[data-category="vedic"]{--accent:#C6A15B;--accent-text:#806125;--green:#C6A15B}
.paj[data-category="birthday"]{--accent:#F0715A;--accent-text:#0E2238;--green:#F0715A}
.paj[data-category="mystic"]{--accent:#6E5AA6;--accent-text:#6E5AA6;--green:#6E5AA6}
.paj[data-category="science"]{--accent:#2F6FB0;--accent-text:#2F6FB0;--green:#2E9E7B;--bg:#FFFFFF;--line:#DDE4EA}

/* The real Navigation + AuthNav header wraps to two rows on narrow viewports. Reserve its
   final height so font-swap / auth-state settling can't push the page down (keeps CLS low). */
@media(max-width:820px){.paj .site-header{min-height:104px;align-content:center;row-gap:4px}}
`;

writeFileSync('src/styles/part-aj.css', header + out.join('\n') + '\n' + overrides);
console.log('Wrote src/styles/part-aj.css —', (header + out.join('\n') + overrides).length, 'bytes');
